name: CI
on:
  push:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - name: Build (arm64)
        run: |
          env GOOS=linux GOARCH=amd64 go build -v ./...

      - name: Build (wasm)
        run: |
          env GOOS=js GOARCH=wasm go build -v ./...

      - name: Lints
        run: |
          go vet -v ./...
